%{
#include <iostream>
#include <vector>
#include <stdio.h>
#include <string.h>
#include <cstddef>
#include "treenode.h"

int yylex(); // A function that is to be generated and provided by flex,
             // which returns a next token when called repeatedly.
int yyerror(const char *p) { std::cerr << "error: " << p << std::endl; };

using namespace asttree;
%}

%union {
   treenode* val;
};

%start prog
%token <val> TERM_OR_NONTERM REWRITES SEMI REP_ZERO_LEFT REP_ZERO_RIGHT ENDL SECTION
%token <val> OPTION_LEFT OPTION_RIGHT
%token <val> GROUPING_LEFT GROUPING_RIGHT GROUP_OR
%token <val> RULE_OR
%token <val> REP_ONE REP_ZERO

%type <val> prog statements statement expr quant rest group_expr conti_rest

%%

prog : SECTION statements SECTION   {  $$ = new prog($1,$2,$3);  /* This adds a node to our own parse tree */
                                       $$->doConversion();
                                       $$->print(cout);
                                    } 
    ;

statements :  statement             {
                                       $$ = new statements($1);  /* This adds a node to our own parse tree */
                                       BNFConverter::statementNode = $$; 
                                    }

    |    statement statements       {  $$ = new statements($1, $2);  /* This adds a node to our own parse tree */ }
    ;

statement : TERM_OR_NONTERM REWRITES rest SEMI  {   $$ = new statement($1,$2,$3,$4); /* This adds a node to our own parse tree */ }
    ;

rest : rest RULE_OR conti_rest { 
                        $$ = new rest($1, $2, $3);
                    }
    |  conti_rest {
        $$ = new rest($1);
            }
    ; 

conti_rest: expr
      {
          $$ = $1;
      }
    | ENDL
      {
          $$ = $1;
      }
    | /* empty */
      {
          $$ = new empty();
      }
    ;

expr : expr quant { 
                    $$ = new expr($1, $2);
                }
     | quant {
                $$ = new expr($1);
            }

    ;


 /* Fill in any other rules here */

group_expr : expr {
                    $$ = new group_expr($1);
                }
           | group_expr GROUP_OR expr {
                    $$ = new group_expr($1, $2, $3);
                }
    ;        


quant : GROUPING_LEFT group_expr GROUPING_RIGHT {
                                            $$ = new quant($1, $2, $3);
                                        }
      | OPTION_LEFT expr OPTION_RIGHT {
                                        $$ = new quant($1, $2, $3);
                                    }
      | REP_ZERO_LEFT expr REP_ZERO_RIGHT {
                                        $$ = new quant($1, $2, $3);
                                    }
      | quant REP_ONE {
                        $$ = new quant($1, $2);
                    }
      | quant REP_ZERO {
                        $$ = new quant($1, $2);
                    }
      | TERM_OR_NONTERM {
                        $$ = new quant($1);
                    }
    ;



%%

int main()
{
    yyparse(); // A parsing function that will be generated by Bison.

    return 0;
}
